# Generated by Django 5.1.6 on 2025-05-21 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('location_preferences', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(choices=[('For Selling a Property', 'for selling a property'), ('For Buying a Property', 'for buying a property'), ('For Rental or Lease', 'for rental or lease'), ('Looking to Rent or Lease Property', 'looking to rent or lease')], max_length=50)),
                ('mode_of_property', models.CharField(max_length=100)),
                ('demand_price', models.IntegerField(blank=True, null=True)),
                ('advance_price', models.IntegerField(blank=True, null=True)),
                ('area_in_sqft', models.CharField(blank=True, max_length=100, null=True)),
                ('area_in_cent', models.CharField(blank=True, max_length=100, null=True)),
                ('building_roof', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_floors', models.CharField(blank=True, null=True)),
                ('building_bhk', models.CharField(blank=True, null=True)),
                ('additional_note', models.CharField(blank=True, max_length=250, null=True)),
                ('location_link', models.CharField(blank=True, max_length=500, null=True)),
                ('lead_category', models.CharField(max_length=200)),
                ('image_folder', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('stage', models.CharField(default='Pending', max_length=100)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('care_of', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingDataPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_pdf', models.FileField(blank=True, null=True, upload_to='match_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='DataBankImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='databank_photos/')),
                ('databank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='databank_section.databank')),
            ],
        ),
        migrations.CreateModel(
            name='LeadDataFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_section.sales_manager_reg')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databank_section.databank')),
            ],
        ),
    ]
