# Generated by Django 5.1.6 on 2025-05-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_event_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, null=True)),
                ('date_time', models.DateTimeField(unique=True)),
                ('priority', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Event_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=200)),
                ('admin_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_section.admin_event_list')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Manager_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, null=True)),
                ('date_time', models.DateTimeField()),
                ('priority', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=150)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_section.sales_manager_reg')),
            ],
            options={
                'unique_together': {('staff', 'date_time')},
            },
        ),
        migrations.CreateModel(
            name='Sales_manager_Event_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_section.sales_manager_event')),
            ],
        ),
    ]
