from django.urls import path
from .views import (get_followeddata_salesmanager,get_detailed_data_salesmanager,salesmanager_purpose_piechart_data,
                    update_databank,successfully_closed_data_salesmanager,unsuccessfully_closed_data_salesmanager,
                    search_databank,filter_data_banks,match_property,pending_data_salesmanager,salesmanager_crm_performance_con,
                    databank_graph,Buy_databank,Sell_databank,ForRent_databank,salesmanager_crm_graph_data,get_new_data,
                    RentSeeker_databank,SalesM_Buy_databank,SalesM_Sell_databank,SalesM_ForRent_databank,add_follower,
                    SalesM_RentSeeker_databank,add_image_databank,view_images_databank,delete_image,Delete_lead,
                    salesmanager_databank_graph,salesmanager_search_databank,admin_single_databank,add_lead_by_admin,
                    admin_view_images_databank,send_matching_pdf,databank_suggestions,Databank_List_admin,
                    autocomplete_databank,autocomplete_databank_salesmanager,Databank,manually_enter_data,import_databank_entry,
                    Follow_lead_data,Update_data_stage,SM_monthly_performance,Admin_crm_performance_graph,Admin_graph_Leads,
                    followed_leads_admin,get_successfullyclosed_leads,get_unsuccessfullyclosed_leads,get_pending_leads,
                    admin_leads_graph_data,lead_category_graph,lead_category_current_month,Sales_lead_category_graph,Sales_lead_category_current_month,
                    )


urlpatterns = [
    path("sales_lead_category_current_month/",Sales_lead_category_current_month,name="Sales_lead_category_current_month,"),
    path("sales_lead_category_graph/",Sales_lead_category_graph,name="Sales_lead_category_graph"),
    path('lead_category_current_month/',lead_category_current_month,name="lead_category_current_month"),
    path('lead_category_graph/',lead_category_graph,name="lead_category_graph"),
    path('admin_leads_graph_data/',admin_leads_graph_data,name="admin_leads_graph_data"),
    path('get_pending_leads/',get_pending_leads,name="get_pending_leads"),
    path('get_unsuccessfullyclosed_leads/',get_unsuccessfullyclosed_leads,name="get_unsuccessfullyclosed_leads"),
    path('get_successfullyclosed_leads/',get_successfullyclosed_leads,name="get_successfullyclosed_leads"),
    path('admin_followed_leads/',followed_leads_admin,name="followed_leads_admin"),
    path('add_lead_by_admin/',add_lead_by_admin,name="add_lead_by_admin"),
    path('delete_lead/<int:lead_id>/',Delete_lead,name="Delete_lead"),
    path('add_follower_data/<int:data_id>/',add_follower,name="add_follower"),
    path('admin_Leads_graph/',Admin_graph_Leads,name="Admin_graph_Leads"),
    path('admin_crm_performance/',Admin_crm_performance_graph,name="Admin_crm_performance_graph"),
    path('SM_monthly_performance/',SM_monthly_performance,name="SM_monthly_performance"),
    path('update_data_stage/<int:data_id>/',Update_data_stage,name="Update_data_stage"),
    path('Follow_lead_data/<int:lead_id>/',Follow_lead_data,name="Follow_lead_data"),
    path('get_new_data/',get_new_data,name="get_new_data"),
    path('import_databank_entry/',import_databank_entry,name="import_databank_entry"),
    path('salesmanger_data_graph/',salesmanager_purpose_piechart_data,name="salesmanger_data_graph"),
    path("datacollection/", manually_enter_data , name="store_data_into_db"),
    path("followedbysalesmanager/", get_followeddata_salesmanager , name="salesmanger_followed"),
    path("detaildata/<int:data_id>/", get_detailed_data_salesmanager , name="get_detailed_data_salesmanager"),
    path('editdata_Databank/<int:databank_id>/',update_databank,name="updatedatabank"),
    path('successfully_closed_leads_salesmanager/',successfully_closed_data_salesmanager,name="successfully_closed_leads_salesmanager"),
    path('unsuccessfully_closed_data_salesmanager/',unsuccessfully_closed_data_salesmanager,name="unsuccessfully_closed_data_salesmanager"),
    path('pending_data_salesmanager/',pending_data_salesmanager,name="pending_data_salesmanager"),
    path('salesmanager_crm_performance/',salesmanager_crm_performance_con,name="salesmanager_crm_performance"),
    path('salesmanager_crm_graph_data/',salesmanager_crm_graph_data,name="salesmanager_crm_graph_data"),
    path('search_in_databank/',search_databank,name="search_databank"),
    path('filter/',filter_data_banks,name="filter_databanks"),
    path('match_property/<int:property_id>/', match_property, name='match_properties'),
    path('databank_graph/',databank_graph,name="databank_graph"),
    path('databank_buy/',Buy_databank,name="buy_databank"),
    path('sell_databank/',Sell_databank,name="sell_databank"),
    path('forrent_databank/',ForRent_databank,name="forrent_databank"),
    path('rental_seeker/',RentSeeker_databank,name="rental_seeker"),
    path('salesmanager_buy_data/',SalesM_Buy_databank,name="salesmanager_buy_data"),
    path('salesmanager_sell_databank/',SalesM_Sell_databank,name="salesmanager_sell"),
    path('salesmanager_forrent_databank/',SalesM_ForRent_databank,name="salesmanager_forrent"),
    path('salesmanager_rentseeker/',SalesM_RentSeeker_databank,name="salesmanger_rentseeker"),
    path('add_image_into_db/<int:databank_id>/',add_image_databank,name="image_add"),
    path('view_images/<int:databank_id>/',view_images_databank,name="view_images"),
    path('delete_image/<int:databank_id>/<int:image_id>/',delete_image,name="delete_image"),
    path('salesmanager_databank_graph/',salesmanager_databank_graph,name="salesmanager_databank_graph"),
    path('search_by_salesmanager/',salesmanager_search_databank,name="salesmanager_search"),
    path('admin_single_databank/<int:databank_id>/',admin_single_databank,name="admin_single_databank"),
    path('admin_view_images/<int:databank_id>/',admin_view_images_databank,name="admin_view_images"),
    path('databank_project_list/',Databank_List_admin,name="databank_project_listing"),
    path('send_matching_pdf/<int:property_id>/',send_matching_pdf,name="sendmatchingpdf"),
    path("suggestions_admin/", databank_suggestions, name="databank_suggestions"),
    path("auto_complete_search_admin/",autocomplete_databank,name="autocomplete"),
    path("salesMSearchAutoComplete/",autocomplete_databank_salesmanager,name="salesMAutoComplete"),
    path("databank_list/",Databank,name="databank")

    
]
